[package]
name = "fixture"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2021"

[dependencies]
anyhow = { workspace = true }
arch = { workspace = true }
base = { workspace = true }
crc32fast = "1.3"
cfg-if = { workspace = true }
libc = { workspace = true }
rand = { workspace = true }
tempfile = "3"
prebuilts = { workspace = true }
log = "0.4"
shlex = "1.3"
url = "2.3"
delegate = {path = "../guest_under_test/rootfs/delegate"}
serde = { workspace = true, features = ["derive"]}
serde_json = { workspace = true }
readclock = { path = "../guest_under_test/rootfs/readclock" }
