[package]
name = "kernel_cmdline"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = { workspace = true }
remain = { workspace = true }
thiserror = { workspace = true }

[lib]
path = "src/kernel_cmdline.rs"
