[package]
name = "audio_streams"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[lib]
path = "src/audio_streams.rs"

[dependencies]
async-trait = "0.1.36"
remain = { workspace = true }
thiserror = { workspace = true }
futures = "0.3"
serde = { workspace = true, features = ["derive"] }
