[package]
name = "vm_control"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[features]
audio = []
balloon = []
gdb = ["gdbstub", "gdbstub_arch"]
gpu = []
pci-hotplug = []
registered_events = ["balloon", "protos/registered_events"]
swap = ["swap/enable"]

[dependencies]
anyhow = { workspace = true }
balloon_control = { workspace = true }
base = { workspace = true }
cfg-if = { workspace = true }
gdbstub = { workspace = true, optional = true }
gdbstub_arch = { workspace = true, optional = true }
hypervisor = { workspace = true }
libc = { workspace = true }
metrics = { workspace = true }
metrics_events = { workspace = true }
protos = { workspace = true, optional = true }
remain = { workspace = true }
resources = { workspace = true }
rutabaga_gfx = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_keyvalue = { workspace = true, features = ["argh_derive"] }
snapshot = { workspace = true }
swap = { workspace = true }
sync = { workspace = true }
thiserror = { workspace = true }
vm_control_product = { path = "../vendor/generic/vm_control", package = "vm_control_product" }
vm_memory = { workspace = true }

[target.'cfg(windows)'.dependencies]
winapi = "0.3"
