[package]
name = "vm_control"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[features]
audio = []
balloon = []
gdb = ["gdbstub", "gdbstub_arch"]
gpu = []
pci-hotplug = []
registered_events = ["balloon", "protos/registered_events"]
swap = ["swap/enable"]

[dependencies]
anyhow = "1"
balloon_control = { workspace = true }
base = { workspace = true }
cfg-if = "1"
gdbstub = { version = "0.7.0", optional = true }
gdbstub_arch = { version = "0.3.0", optional = true }
hypervisor = { workspace = true }
libc = { workspace = true }
metrics = { workspace = true }
metrics_events = { workspace = true }
protos = { workspace = true, optional = true }
remain = "0.2"
resources = { workspace = true }
rutabaga_gfx = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_keyvalue = { workspace = true, features = ["argh_derive"] }
snapshot = { workspace = true }
swap = { workspace = true }
sync = { workspace = true }
thiserror = "1"
vm_control_product = { path = "../vendor/generic/vm_control", package = "vm_control_product" }
vm_memory = { workspace = true }

[target.'cfg(windows)'.dependencies]
winapi = "0.3"
