[package]
name = "kvm_sys"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[dependencies]
data_model = { workspace = true }
libc = { workspace = true }
base = { workspace = true }
zerocopy = { version = "0.8.13", features = ["derive"] }
