[package]
name = "snapshot"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[features]

[dependencies]
anyhow = "1"
base = { workspace = true }
crypto = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ciborium = { workspace = true }
