[package]
name = "snapshot"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[features]

[dependencies]
anyhow = { workspace = true }
base = { workspace = true }
crypto = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
ciborium = { workspace = true }
