[package]
name = "x86_64"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[features]
gdb = ["gdbstub_arch", "arch/gdb"]
seccomp_trace = []
swap = ["swap/enable"]

[dependencies]
acpi_tables = { workspace = true }
arch = { workspace = true }
anyhow = { workspace = true }
cfg-if = { workspace = true }
chrono = { version = "0.4.34", default-features = false }
cros_fdt = { workspace = true }
devices = { workspace = true }
gdbstub_arch = { workspace = true, optional = true }
hypervisor = { workspace = true }
jail = { path = "../jail" }
kernel_cmdline = { workspace = true }
kernel_loader = { workspace = true }
libc = { workspace = true }
rand = { workspace = true }
remain = { workspace = true }
resources = { workspace = true }
sync = { workspace = true }
thiserror = { workspace = true }
uuid = { version = "1", features = ["v4"] }
base = { workspace = true }
swap = { workspace = true }
vm_control = { workspace = true }
vm_memory = { workspace = true }
zerocopy = { version = "0.8.13", features = ["derive"] }

[target.'cfg(any(target_os = "android", target_os = "linux"))'.dependencies]
minijail = "*"
