# Disable clippy lints project-wide.
# This allows ./tools/clippy and IDE integrations to use the same configuration.
# This should be replaced with a proper clippy config once available:
# https://github.com/rust-lang/cargo/issues/5034
[build]
rustflags = [
    # We don't care about these lints. Okay to remain suppressed globally.
    "-Aclippy::bool_assert_comparison",
    "-Aclippy::cast_lossless",
    "-Aclippy::cognitive_complexity",
    "-Aclippy::collapsible_if",
    "-Aclippy::enum_variant_names",
    "-Aclippy::identity_op",
    "-Aclippy::needless_bool",
    "-Aclippy::new-ret-no-self",
    "-Aclippy::result_large_err",
    "-Aclippy::result-unit-err",
    "-Aclippy::single-range-in-vec-init",
    "-Aclippy::too_many_arguments",
    "-Aclippy::type_complexity",
    "-Aclippy::unreadable_literal",
    "-Aclippy::useless_transmute",
    "-Dclippy::undocumented_unsafe_blocks",
]

[env]

# The downstream can use these environment variables to set the gfxstream libraries search path.
GFXSTREAM_PATH_DEBUG = ""
GFXSTREAM_PATH_RELEASE = ""
