[package]
name = "ffmpeg"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[dependencies]
anyhow = { workspace = true }
libc = { workspace = true }
thiserror = { workspace = true }

[build-dependencies]
bindgen = "0.63"
pkg-config = "0.3"
