[package]
name = "linux_input_sys"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[dependencies]
data_model = { path = "../common/data_model" }
libc = { workspace = true }
base = { workspace = true }
zerocopy = { version = "0.8.13", features = ["derive"] }
