[package]
name = "riscv64"
version = "0.1.0"
authors = ["Rivos Inc."]
edition = "2021"

[features]
gdb = ["gdbstub", "gdbstub_arch", "arch/gdb"]
swap = ["swap/enable"]

[dependencies]
arch = { workspace = true }
cros_fdt = { workspace = true }
devices = { workspace = true }
gdbstub = { version = "0.7.0", optional = true }
gdbstub_arch = { version = "0.3.0", optional = true }
hypervisor = { workspace = true }
kernel_cmdline = { workspace = true }
libc = { workspace = true }
rand = "0.8"
remain = "0.2"
resources = { workspace = true }
swap = { workspace = true }
sync = { workspace = true }
thiserror = "1"
base = { workspace = true }
vm_control = { workspace = true }
vm_memory = { workspace = true }

[target.'cfg(any(target_os = "android", target_os = "linux"))'.dependencies]
minijail = "*"
