[package]
name = "riscv64"
version = "0.1.0"
authors = ["Rivos Inc."]
edition = "2021"

[features]
gdb = ["gdbstub", "gdbstub_arch", "arch/gdb"]
swap = ["swap/enable"]

[dependencies]
arch = { workspace = true }
cros_fdt = { workspace = true }
devices = { workspace = true }
gdbstub = { workspace = true, optional = true }
gdbstub_arch = { workspace = true, optional = true }
hypervisor = { workspace = true }
kernel_cmdline = { workspace = true }
libc = { workspace = true }
rand = { workspace = true }
remain = { workspace = true }
resources = { workspace = true }
swap = { workspace = true }
sync = { workspace = true }
thiserror = { workspace = true }
base = { workspace = true }
vm_control = { workspace = true }
vm_memory = { workspace = true }

[target.'cfg(any(target_os = "android", target_os = "linux"))'.dependencies]
minijail = "*"
