[package]
name = "io_uring"
version = "0.1.1"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[dependencies]
libc = { workspace = true }
remain = "0.2"
sync = { workspace = true }
base = { workspace = true }
thiserror = "1"

[dev-dependencies]
tempfile = "3"


