# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

[package]
name = "readclock"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2021"

[dependencies]
anyhow = { workspace = true }
libc = { workspace = true }
serde = { workspace = true, features = ["derive"]}
serde_json = { workspace = true }
