[package]
name = "proc_init"
authors = ["The ChromiumOS Authors"]
version = "0.1.0"
edition = "2021"

[features]
crash-report = ["crash_report", "proc_init_product/crash-report"]
process-invariants = ["proc_init_product/process-invariants"]

[dependencies]
anyhow = { workspace = true }
base = { workspace = true }
crash_report = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
metrics = { workspace = true }
proc_init_product = { path = "../vendor/generic/proc_init/" }
