[package]
name = "serde_keyvalue"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[features]
argh_derive = ["argh", "serde_keyvalue_derive"]

[dependencies]
argh = { workspace = true, optional = true }
serde_keyvalue_derive = { path = "serde_keyvalue_derive", optional = true }
serde = { workspace = true }
thiserror = { workspace = true }
remain = { workspace = true }
num-traits = "0.2"
nom = { version = "7.1.0", features = ["alloc"] }

[dev-dependencies]
serde = { workspace = true, features = ["derive"] }
