[package]
name = "win_audio"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[target.'cfg(windows)'.dependencies]
async-trait = "0.1.36"
audio_streams = { workspace = true }
audio_util = { workspace = true }
base = { workspace = true }
cros_async = { workspace = true }
libc = { workspace = true }
win_util = { path = "../win_util" }
winapi = "0.3"
wio = "0.2"
sync = { workspace = true }
thiserror = { workspace = true }
metrics = { workspace = true }

[build-dependencies]
anyhow = { workspace = true }
prebuilts = { workspace = true }

