[package]
name = "win_util"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[dependencies]
anyhow = { workspace = true }
enumn = { workspace = true }
libc = { workspace = true }
# Note most crates in this project use re-exported log macros from base, but
# as this crate is a base dependency, we use log directly
log = "0.4"
serde = { workspace = true, features = [ "derive" ] }
zeroize = "1.5.7"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["everything", "std", "impl-default"] }

[dependencies.windows]
version = "0.39.0"
features = [
    "Win32_Foundation",
    "Win32_Globalization",
    "Win32_Graphics_Gdi",
    "Win32_UI_Input_Ime",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_TextServices",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Com",
]

[build-dependencies.windows]
version = "0.39.0"
features = [
    "Win32_Foundation",
    "Win32_Globalization",
    "Win32_Graphics_Gdi",
    "Win32_UI_Input_Ime",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_TextServices",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Com",
]

[dev-dependencies]
libloading = "0.7.3"
