[package]
name = "vm_memory"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"
include = ["src/**/*", "Cargo.toml"]

[dependencies]
anyhow = { workspace = true }
cfg-if = { workspace = true }
cros_async = { workspace = true }
data_model = { workspace = true }
libc = { workspace = true }
lz4_flex = "0.11"
base = { workspace = true }
bitflags = "2.2.1"
remain = { workspace = true }
serde = { workspace = true, features = [ "derive" ] }
serde_json = { workspace = true }
serde_keyvalue = { workspace = true, features = ["argh_derive"] }
snapshot = { workspace = true }
thiserror = { workspace = true }
zerocopy = { version = "0.8.13", features = ["derive"] }

[dev-dependencies]
tempfile = "3"
